### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by jbaubree** [StatuAgency/unocss-preset-grid#1]
Hi 👋 

There is an issue with typing in your preset.
When importing `unocss-preset-grid`, we get following typescript error:
`Cannot find module 'unocss-preset-grid' or its corresponding type declarations.`
This is due to your package.json configuration that declares `"types": "./dist/index.d.ts"` without anything creating this index.d.ts on build.
Can you fix this?

Thanks in advance

**Comment by berkaltiok** [comment]
Hello,
We are aware of this mistake. We will solve this problem as soon as possible. If you want to contribute to the project and solve the problem, we would be very happy.
